import csv
import random

# Sample sentences for each sentiment
happy_sentences = [
    "I'm feeling absolutely delighted today!",
    "I'm just so god damn elated.",
    "What a wonderful day it is.",
    "I am in a great mood right now.",
    "I'm absolutely thrilled today!",
    "Everything is going wonderfully!",
    "I couldn't be happier with how things are going!",
    "This is such a delightful day!",
    "I'm brimming with joy and excitement!",
    "Feeling incredibly pleased with everything!",
    "What a splendid time I'm having!",
    "I'm on top of the world right now!",
    "Today has been an absolute dream!",
    "I'm so grateful for all the good in my life!",
    "Feeling so lucky and blessed today!",
    "It's a day full of smiles and laughter!",
    "I'm glowing with happiness!",
    "Every moment today is a joy!",
    "I'm so happy I could sing!",
    "Today is full of pleasant surprises!",
    "I'm surrounded by so much positivity!",
    "Feeling fantastic and full of life!",
    "My heart is overflowing with joy!",
    "This is one of the best days of my life!",
    "I'm cherishing every moment today!",
    "Feeling so upbeat and enthusiastic!",
    "I'm just radiating happiness today!",
    "What a fabulous day it's been!",
    "I'm feeling incredibly cheerful and lively!",
    "Everything feels so right and perfect!",
    "I'm in such a great mood today!",
    "This happiness is just unbeatable!",
    "I'm experiencing pure bliss!",
    "Feeling so content and fulfilled!",
    "It's a beautiful day to be happy!",
    "My spirits are soaring high today!",
    "Feeling like the happiest person in the world!",
    "I'm just basking in this joyous moment!",
    "So much happiness, so much fun!",
    "I'm loving every second of today!",
    "This joy is just contagious!",
    "Feeling super excited about everything!",
    "It's a genuinely fantastic feeling!",
    "I'm savoring this wave of happiness!",
    "What a joyous and wonderful day!",
    "Every moment is a reason to smile!",
    "I'm filled with so much happiness!",
    "Feeling absolutely blissful right now!",
    "It's a day of pure joy and laughter!",
    "I'm just loving life to the fullest!",
    "Every bit of today is just perfect!",
    "Feeling so joyful and alive!",
    "This delight is just overwhelming!",
    "I'm in a state of pure euphoria!",
    "Feeling so happy, nothing can bring me down!",
    "It's a day to remember for all the joy!",
    "Happiness is all around me today!",
    "I'm just so happy I could cry!",
]

sad_sentences = [
    "I'm feeling really down today.",
    "It's a gloomy and sad day for me.",
    "Nothing seems to cheer me up.",
    "I feel like there's a cloud hanging over me today.",
    "Everything seems so bleak and hopeless.",
    "I'm struggling to find any joy in things I usually love.",
    "Today has been filled with nothing but disappointment.",
    "I feel so alone and isolated right now.",
    "It's like a shadow has fallen over my heart.",
    "I'm overwhelmed with a sense of sadness.",
    "There's a heaviness in my soul today.",
    "I can't seem to shake off this feeling of despair.",
    "It feels like the world is just a dark place.",
    "My heart feels heavy with sorrow.",
    "I'm lost in a sea of sadness.",
    "Every smile feels forced and empty.",
    "Nobody gives a damn about me.",
    "I'm drowning in my own tears.",
    "It's like all the color has drained from the world.",
    "I'm just going through the motions, feeling numb.",
    "The weight of sadness is crushing me.",
    "I feel so helpless and hopeless.",
    "It's hard to see any light in this darkness.",
    "I'm suffocating under all this sadness.",
    "Every day feels more difficult than the last.",
    "I'm just so tired of feeling this way.",
    "It feels like I'm walking through a never-ending storm.",
    "I can't find the strength to smile today.",
    "The world feels cold and unforgiving.",
    "I'm struggling to hold back the tears.",
    "There's a constant ache in my heart.",
    "I feel like I'm losing myself in this sadness.",
    "Nothing seems to matter anymore.",
    "I'm trapped in a fog of sorrow.",
    "I can't escape these feelings of despair.",
    "Every laugh feels hollow and meaningless.",
    "I'm just so sad and I don't know why.",
    "It's like happiness is just out of reach.",
    "I'm living in a nightmare I can't wake up from.",
    "The pain of sadness is overwhelming.",
    "I'm caught in a downpour of despair.",
    "I feel so broken inside.",
    "Every day is a struggle against sadness.",
    "I'm fading away in this sea of sorrow.",
    "The darkness of sadness is all-consuming.",
    "I feel so disconnected from everything.",
    "My world is crumbling around me.",
    "I'm sinking deeper into sadness.",
    "The tears just won't stop falling.",
    "I'm enveloped in a blanket of sorrow.",
    "I can't remember the last time I felt happy.",
    "I'm just so overwhelmed with sadness.",
    "It feels like my heart is breaking.",
    "I'm lost in the depths of despair.",
    "I'm so tired of feeling this way.",
]

angry_sentences = [
    "Everything is just annoying me today.",
    "I'm so frustrated with everything!",
    "Why can't things just go right for once?",
    "Fuck everything and everone.",
    "I can't believe this shit!",
    "I'm so angry I could scream!",
    "I'm sick and tired of all this nonsense!",
    "I can't believe how unfair this is!",
    "Everything is just infuriating me right now!",
    "I'm so tired of being taken for granted!",
    "Why does this always have to happen to me?",
    "I've had enough of this nonsense!",
    "It's like no one cares about how I feel!",
    "I'm just so frustrated and angry!",
    "Nobody ever listens to me!",
    "I'm sick of being ignored!",
    "This is just beyond annoying!",
    "I feel like I'm about to explode!",
    "I can't take this anymore!",
    "Why can't things just go my way for once?",
    "I'm so done with all of this!",
    "It feels like everyone is against me!",
    "I'm just so angry I can't even think straight!",
    "I hate how things are going right now!",
    "This is absolutely ridiculous!",
    "I'm boiling with anger!",
    "I've never been this upset in my life!",
    "It feels like I'm fighting a losing battle!",
    "I'm just filled with rage!",
    "Why is everything so complicated?",
    "I feel betrayed and let down!",
    "This is the last straw!",
    "I'm at my wit's end!",
    "I can't stand this anymore!",
    "I'm so fed up with everything!",
    "Why does this always happen to me?",
    "I'm losing my patience!",
    "I'm so angry, I can barely speak!",
    "This is completely unacceptable!",
    "I'm just sick of all these problems!",
    "It's like nobody understands!",
    "I'm tired of being pushed around!",
    "I'm on the edge of losing it!",
    "This is making me so mad!",
    "I'm so annoyed I can't focus!",
    "I feel like screaming in frustration!",
    "I can't believe I'm being treated this way!",
    "I'm just filled with so much anger!",
    "I'm at the end of my rope!",
    "I'm so infuriated right now!",
    "I've had it up to here with this!",
    "I'm not going to take this anymore!",
    "This is driving me crazy!",
    "I'm so angry, I'm shaking!",
    "I can't deal with this level of frustration!",
    "I'm so outraged by this!",
    "I'm just so angry about everything!",
    "I'm so pissed off right now!",
    "I'm just so sick of all this bullshit!",
    "Say that again, motherfucker.",
    "What the fuck is wrong with everyone?"
]

neutral_sentences = [
    "I'm just going through my daily routine.",
    "It's just a regular day, nothing special.",
    "I am working on my tasks.",
    "Can't complain either way.",
    "I'm just doing what I do every day.",
    "I'm just doing my usual thing.",
    "Nothing out of the ordinary is happening.",
    "I'm just going about my business.",
    "I'm just reading a book right now.",
    "I'm going about my day as usual.",
    "Just doing some chores around the house.",
    "I'm in the middle of working on a project.",
    "Just a regular day at work.",
    "I'm commuting to my office.",
    "I'm preparing a meal.",
    "Just taking a walk in the park.",
    "I'm shopping for groceries.",
    "Just watching some TV.",
    "I'm answering some emails.",
    "I'm attending a meeting.",
    "Just sitting and relaxing for a bit.",
    "I'm cleaning up the kitchen.",
    "I'm doing some gardening.",
    "Just working on my computer.",
    "I'm studying for an exam.",
    "I'm having lunch right now.",
    "Just listening to some music.",
    "I'm making a cup of coffee.",
    "I'm reading the news.",
    "Just waiting for a friend.",
    "I'm walking my dog.",
    "I'm working out at the gym.",
    "Just taking a short break.",
    "I'm writing a report.",
    "I'm organizing my room.",
    "Just browsing the internet.",
    "I'm calling a friend.",
    "I'm waiting for a delivery.",
    "Just looking out the window.",
    "I'm planning my schedule.",
    "I'm checking my messages.",
    "Just enjoying a quiet evening.",
    "I'm fixing something in the house.",
    "I'm trying a new recipe.",
    "Just running some errands.",
    "I'm watching a documentary.",
    "I'm packing for a trip.",
    "Just learning something new online.",
    "I'm sorting my files.",
    "I'm checking the weather forecast.",
    "Just watering the plants.",
    "I'm ironing my clothes.",
    "I'm watching the sunset.",
    "Just thinking about my plans.",
    "I'm having a snack.",
    "I'm updating my to-do list.",
    "Just stretching a bit.",
    "I'm looking for a book to read."
    # Add more neutral sentences
]

# Combining all sentences
all_sentences = [(sentence, 'happy') for sentence in happy_sentences] + \
                [(sentence, 'sad') for sentence in sad_sentences] + \
                [(sentence, 'angry') for sentence in angry_sentences] + \
                [(sentence, 'neutral') for sentence in neutral_sentences]

# Shuffle the dataset for randomness
random.shuffle(all_sentences)

# Writing to a CSV file
with open('sentiment_dataset.csv', 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Sentence', 'Sentiment'])  # Writing header
    writer.writerows(all_sentences)

print("Dataset generated and saved to 'sentiment_dataset.csv'")